// Code generated by MockGen. DO NOT EDIT.
// Source: contracts\contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNetHttpHandler is a mock of NetHttpHandler interface.
type MockNetHttpHandler struct {
	ctrl     *gomock.Controller
	recorder *MockNetHttpHandlerMockRecorder
}

// MockNetHttpHandlerMockRecorder is the mock recorder for MockNetHttpHandler.
type MockNetHttpHandlerMockRecorder struct {
	mock *MockNetHttpHandler
}

// NewMockNetHttpHandler creates a new mock instance.
func NewMockNetHttpHandler(ctrl *gomock.Controller) *MockNetHttpHandler {
	mock := &MockNetHttpHandler{ctrl: ctrl}
	mock.recorder = &MockNetHttpHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetHttpHandler) EXPECT() *MockNetHttpHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNetHttpHandler) Create(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", w, r)
}

// Create indicates an expected call of Create.
func (mr *MockNetHttpHandlerMockRecorder) Create(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNetHttpHandler)(nil).Create), w, r)
}

// Delete mocks base method.
func (m *MockNetHttpHandler) Delete(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", w, r)
}

// Delete indicates an expected call of Delete.
func (mr *MockNetHttpHandlerMockRecorder) Delete(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNetHttpHandler)(nil).Delete), w, r)
}

// Get mocks base method.
func (m *MockNetHttpHandler) Get(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Get", w, r)
}

// Get indicates an expected call of Get.
func (mr *MockNetHttpHandlerMockRecorder) Get(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNetHttpHandler)(nil).Get), w, r)
}

// List mocks base method.
func (m *MockNetHttpHandler) List(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "List", w, r)
}

// List indicates an expected call of List.
func (mr *MockNetHttpHandlerMockRecorder) List(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNetHttpHandler)(nil).List), w, r)
}

// Save mocks base method.
func (m *MockNetHttpHandler) Save(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", w, r)
}

// Save indicates an expected call of Save.
func (mr *MockNetHttpHandlerMockRecorder) Save(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockNetHttpHandler)(nil).Save), w, r)
}

// Update mocks base method.
func (m *MockNetHttpHandler) Update(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", w, r)
}

// Update indicates an expected call of Update.
func (mr *MockNetHttpHandlerMockRecorder) Update(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNetHttpHandler)(nil).Update), w, r)
}
