// Code generated by MockGen. DO NOT EDIT.
// Source: ..\..\..\pkg\repositories\rest\contracts\contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	contracts "github.com/brunojet/go-infra-ports/pkg/repositories/rest/contracts"
	types "github.com/brunojet/go-infra-ports/pkg/types"
	gomock "github.com/golang/mock/gomock"
)

// MockRestRequestSpec is a mock of RestRequestSpec interface.
type MockRestRequestSpec struct {
	ctrl     *gomock.Controller
	recorder *MockRestRequestSpecMockRecorder
}

// MockRestRequestSpecMockRecorder is the mock recorder for MockRestRequestSpec.
type MockRestRequestSpecMockRecorder struct {
	mock *MockRestRequestSpec
}

// NewMockRestRequestSpec creates a new mock instance.
func NewMockRestRequestSpec(ctrl *gomock.Controller) *MockRestRequestSpec {
	mock := &MockRestRequestSpec{ctrl: ctrl}
	mock.recorder = &MockRestRequestSpecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestRequestSpec) EXPECT() *MockRestRequestSpecMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockRestRequestSpec) New() contracts.RestRequestSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(contracts.RestRequestSpec)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockRestRequestSpecMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockRestRequestSpec)(nil).New))
}

// SetBody mocks base method.
func (m *MockRestRequestSpec) SetBody(body contracts.RestRequestSpec) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBody", body)
}

// SetBody indicates an expected call of SetBody.
func (mr *MockRestRequestSpecMockRecorder) SetBody(body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBody", reflect.TypeOf((*MockRestRequestSpec)(nil).SetBody), body)
}

// MockRestResponseSpec is a mock of RestResponseSpec interface.
type MockRestResponseSpec struct {
	ctrl     *gomock.Controller
	recorder *MockRestResponseSpecMockRecorder
}

// MockRestResponseSpecMockRecorder is the mock recorder for MockRestResponseSpec.
type MockRestResponseSpecMockRecorder struct {
	mock *MockRestResponseSpec
}

// NewMockRestResponseSpec creates a new mock instance.
func NewMockRestResponseSpec(ctrl *gomock.Controller) *MockRestResponseSpec {
	mock := &MockRestResponseSpec{ctrl: ctrl}
	mock.recorder = &MockRestResponseSpecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestResponseSpec) EXPECT() *MockRestResponseSpecMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockRestResponseSpec) New() contracts.RestResponseSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(contracts.RestResponseSpec)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockRestResponseSpecMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockRestResponseSpec)(nil).New))
}

// NewSlice mocks base method.
func (m *MockRestResponseSpec) NewSlice(n int) []contracts.RestResponseSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSlice", n)
	ret0, _ := ret[0].([]contracts.RestResponseSpec)
	return ret0
}

// NewSlice indicates an expected call of NewSlice.
func (mr *MockRestResponseSpecMockRecorder) NewSlice(n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSlice", reflect.TypeOf((*MockRestResponseSpec)(nil).NewSlice), n)
}

// MockRestEnvelopeSpec is a mock of RestEnvelopeSpec interface.
type MockRestEnvelopeSpec struct {
	ctrl     *gomock.Controller
	recorder *MockRestEnvelopeSpecMockRecorder
}

// MockRestEnvelopeSpecMockRecorder is the mock recorder for MockRestEnvelopeSpec.
type MockRestEnvelopeSpecMockRecorder struct {
	mock *MockRestEnvelopeSpec
}

// NewMockRestEnvelopeSpec creates a new mock instance.
func NewMockRestEnvelopeSpec(ctrl *gomock.Controller) *MockRestEnvelopeSpec {
	mock := &MockRestEnvelopeSpec{ctrl: ctrl}
	mock.recorder = &MockRestEnvelopeSpecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestEnvelopeSpec) EXPECT() *MockRestEnvelopeSpecMockRecorder {
	return m.recorder
}

// EnvelopeData mocks base method.
func (m *MockRestEnvelopeSpec) EnvelopeData() json.RawMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnvelopeData")
	ret0, _ := ret[0].(json.RawMessage)
	return ret0
}

// EnvelopeData indicates an expected call of EnvelopeData.
func (mr *MockRestEnvelopeSpecMockRecorder) EnvelopeData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnvelopeData", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).EnvelopeData))
}

// EnvelopeMeta mocks base method.
func (m *MockRestEnvelopeSpec) EnvelopeMeta() types.ResponseMeta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnvelopeMeta")
	ret0, _ := ret[0].(types.ResponseMeta)
	return ret0
}

// EnvelopeMeta indicates an expected call of EnvelopeMeta.
func (mr *MockRestEnvelopeSpecMockRecorder) EnvelopeMeta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnvelopeMeta", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).EnvelopeMeta))
}

// New mocks base method.
func (m *MockRestEnvelopeSpec) New() contracts.RestEnvelopeSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(contracts.RestEnvelopeSpec)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockRestEnvelopeSpecMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).New))
}

// MockRestRegistry is a mock of RestRegistry interface.
type MockRestRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRestRegistryMockRecorder
}

// MockRestRegistryMockRecorder is the mock recorder for MockRestRegistry.
type MockRestRegistryMockRecorder struct {
	mock *MockRestRegistry
}

// NewMockRestRegistry creates a new mock instance.
func NewMockRestRegistry(ctrl *gomock.Controller) *MockRestRegistry {
	mock := &MockRestRegistry{ctrl: ctrl}
	mock.recorder = &MockRestRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestRegistry) EXPECT() *MockRestRegistryMockRecorder {
	return m.recorder
}

// Merge mocks base method.
func (m *MockRestRegistry) Merge(other contracts.RestRegistry) contracts.RestRegistry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", other)
	ret0, _ := ret[0].(contracts.RestRegistry)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockRestRegistryMockRecorder) Merge(other interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockRestRegistry)(nil).Merge), other)
}

// NewRequestSpec mocks base method.
func (m *MockRestRegistry) NewRequestSpec(name string) (contracts.RestRequestSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRequestSpec", name)
	ret0, _ := ret[0].(contracts.RestRequestSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewRequestSpec indicates an expected call of NewRequestSpec.
func (mr *MockRestRegistryMockRecorder) NewRequestSpec(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRequestSpec", reflect.TypeOf((*MockRestRegistry)(nil).NewRequestSpec), name)
}

// ReleaseRequestSpec mocks base method.
func (m *MockRestRegistry) ReleaseRequestSpec(spec contracts.RestRequestSpec) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReleaseRequestSpec", spec)
}

// ReleaseRequestSpec indicates an expected call of ReleaseRequestSpec.
func (mr *MockRestRegistryMockRecorder) ReleaseRequestSpec(spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseRequestSpec", reflect.TypeOf((*MockRestRegistry)(nil).ReleaseRequestSpec), spec)
}

// ResolveEnvelopeRequest mocks base method.
func (m *MockRestRegistry) ResolveEnvelopeRequest(name string, dataBody *[]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEnvelopeRequest", name, dataBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveEnvelopeRequest indicates an expected call of ResolveEnvelopeRequest.
func (mr *MockRestRegistryMockRecorder) ResolveEnvelopeRequest(name, dataBody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEnvelopeRequest", reflect.TypeOf((*MockRestRegistry)(nil).ResolveEnvelopeRequest), name, dataBody)
}

// ResolveEnvelopeResponse mocks base method.
func (m *MockRestRegistry) ResolveEnvelopeResponse(status int, dataBody *[]byte, meta *types.ResponseMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEnvelopeResponse", status, dataBody, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveEnvelopeResponse indicates an expected call of ResolveEnvelopeResponse.
func (mr *MockRestRegistryMockRecorder) ResolveEnvelopeResponse(status, dataBody, meta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEnvelopeResponse", reflect.TypeOf((*MockRestRegistry)(nil).ResolveEnvelopeResponse), status, dataBody, meta)
}

// ResolveRequest mocks base method.
func (m *MockRestRegistry) ResolveRequest(body contracts.RestRequestSpec, requestBody *[]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRequest", body, requestBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveRequest indicates an expected call of ResolveRequest.
func (mr *MockRestRegistryMockRecorder) ResolveRequest(body, requestBody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRequest", reflect.TypeOf((*MockRestRegistry)(nil).ResolveRequest), body, requestBody)
}

// ResolveResponse mocks base method.
func (m *MockRestRegistry) ResolveResponse(status int, responseBody []byte, body *contracts.RestResponseSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveResponse", status, responseBody, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveResponse indicates an expected call of ResolveResponse.
func (mr *MockRestRegistryMockRecorder) ResolveResponse(status, responseBody, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveResponse", reflect.TypeOf((*MockRestRegistry)(nil).ResolveResponse), status, responseBody, body)
}

// ResolveResponses mocks base method.
func (m *MockRestRegistry) ResolveResponses(status int, responseBody []byte, bodies *[]contracts.RestResponseSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveResponses", status, responseBody, bodies)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveResponses indicates an expected call of ResolveResponses.
func (mr *MockRestRegistryMockRecorder) ResolveResponses(status, responseBody, bodies interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveResponses", reflect.TypeOf((*MockRestRegistry)(nil).ResolveResponses), status, responseBody, bodies)
}

// MockRestRepository is a mock of RestRepository interface.
type MockRestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRestRepositoryMockRecorder
}

// MockRestRepositoryMockRecorder is the mock recorder for MockRestRepository.
type MockRestRepositoryMockRecorder struct {
	mock *MockRestRepository
}

// NewMockRestRepository creates a new mock instance.
func NewMockRestRepository(ctrl *gomock.Controller) *MockRestRepository {
	mock := &MockRestRepository{ctrl: ctrl}
	mock.recorder = &MockRestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestRepository) EXPECT() *MockRestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRestRepository) Create(ctx context.Context, request contracts.RestRequest, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRestRepositoryMockRecorder) Create(ctx, request, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRestRepository)(nil).Create), ctx, request, response)
}

// Delete mocks base method.
func (m *MockRestRepository) Delete(ctx context.Context, reqCtx types.RequestContext, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRestRepositoryMockRecorder) Delete(ctx, reqCtx, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRestRepository)(nil).Delete), ctx, reqCtx, response)
}

// Get mocks base method.
func (m *MockRestRepository) Get(ctx context.Context, reqCtx types.RequestContext, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRestRepositoryMockRecorder) Get(ctx, reqCtx, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRestRepository)(nil).Get), ctx, reqCtx, response)
}

// List mocks base method.
func (m *MockRestRepository) List(ctx context.Context, reqCtx types.RequestContext, response *contracts.RestResponses) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockRestRepositoryMockRecorder) List(ctx, reqCtx, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRestRepository)(nil).List), ctx, reqCtx, response)
}

// Save mocks base method.
func (m *MockRestRepository) Save(ctx context.Context, request contracts.RestRequest, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRestRepositoryMockRecorder) Save(ctx, request, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRestRepository)(nil).Save), ctx, request, response)
}

// Update mocks base method.
func (m *MockRestRepository) Update(ctx context.Context, request contracts.RestRequest, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRestRepositoryMockRecorder) Update(ctx, request, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRestRepository)(nil).Update), ctx, request, response)
}
