// Code generated by MockGen. DO NOT EDIT.
// Source: ..\contracts\contracts.go
//
// Generated by this command:
//
//	mockgen --source ..\contracts\contracts.go --destination mocks.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	contracts "github.com/brunojet/go-infra-ports/pkg/repositories/rest/contracts"
	types "github.com/brunojet/go-infra-ports/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// permissiveDataSpec is a lightweight RestDataSpec implementation used by the generated
// mocks to provide a non-nil, permissive data spec that accepts any body value.
type permissiveDataSpec struct {
	v any
}

func (p *permissiveDataSpec) New() contracts.RestDataSpec { return &permissiveDataSpec{} }
func (p *permissiveDataSpec) NewSlice(n int) []contracts.RestDataSpec {
	out := make([]contracts.RestDataSpec, n)
	for i := range out {
		out[i] = &permissiveDataSpec{}
	}
	return out
}
func (p *permissiveDataSpec) SetBody(body any) error       { p.v = body; return nil }
func (p *permissiveDataSpec) Body() any                    { return p.v }
func (p *permissiveDataSpec) MarshalJSON() ([]byte, error) { return json.Marshal(p.v) }
func (p *permissiveDataSpec) UnmarshalJSON(data []byte) error {
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	p.v = v
	return nil
}

// MockRestDataSpec is a mock of RestDataSpec interface.
type MockRestDataSpec struct {
	ctrl     *gomock.Controller
	recorder *MockRestDataSpecMockRecorder
	isgomock struct{}
}

// MockRestDataSpecMockRecorder is the mock recorder for MockRestDataSpec.
type MockRestDataSpecMockRecorder struct {
	mock *MockRestDataSpec
}

// NewMockRestDataSpec creates a new mock instance.
func NewMockRestDataSpec(ctrl *gomock.Controller) *MockRestDataSpec {
	mock := &MockRestDataSpec{ctrl: ctrl}
	mock.recorder = &MockRestDataSpecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestDataSpec) EXPECT() *MockRestDataSpecMockRecorder {
	return m.recorder
}

// Body mocks base method.
func (m *MockRestDataSpec) Body() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body")
	ret0, _ := ret[0].(any)
	return ret0
}

// Body indicates an expected call of Body.
func (mr *MockRestDataSpecMockRecorder) Body() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockRestDataSpec)(nil).Body))
}

// MarshalJSON mocks base method.
func (m *MockRestDataSpec) MarshalJSON() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalJSON")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalJSON indicates an expected call of MarshalJSON.
func (mr *MockRestDataSpecMockRecorder) MarshalJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalJSON", reflect.TypeOf((*MockRestDataSpec)(nil).MarshalJSON))
}

// New mocks base method.
func (m *MockRestDataSpec) New() contracts.RestDataSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(contracts.RestDataSpec)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockRestDataSpecMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockRestDataSpec)(nil).New))
}

// NewSlice mocks base method.
func (m *MockRestDataSpec) NewSlice(n int) []contracts.RestDataSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSlice", n)
	ret0, _ := ret[0].([]contracts.RestDataSpec)
	return ret0
}

// NewSlice indicates an expected call of NewSlice.
func (mr *MockRestDataSpecMockRecorder) NewSlice(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSlice", reflect.TypeOf((*MockRestDataSpec)(nil).NewSlice), n)
}

// SetBody mocks base method.
func (m *MockRestDataSpec) SetBody(body any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBody", body)
}

// SetBody indicates an expected call of SetBody.
func (mr *MockRestDataSpecMockRecorder) SetBody(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBody", reflect.TypeOf((*MockRestDataSpec)(nil).SetBody), body)
}

// UnmarshalJSON mocks base method.
func (m *MockRestDataSpec) UnmarshalJSON(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalJSON", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalJSON indicates an expected call of UnmarshalJSON.
func (mr *MockRestDataSpecMockRecorder) UnmarshalJSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalJSON", reflect.TypeOf((*MockRestDataSpec)(nil).UnmarshalJSON), data)
}

// MockRestEnvelopeSpec is a mock of RestEnvelopeSpec interface.
type MockRestEnvelopeSpec struct {
	ctrl     *gomock.Controller
	recorder *MockRestEnvelopeSpecMockRecorder
	isgomock struct{}
}

// MockRestEnvelopeSpecMockRecorder is the mock recorder for MockRestEnvelopeSpec.
type MockRestEnvelopeSpecMockRecorder struct {
	mock *MockRestEnvelopeSpec
}

// NewMockRestEnvelopeSpec creates a new mock instance.
func NewMockRestEnvelopeSpec(ctrl *gomock.Controller) *MockRestEnvelopeSpec {
	mock := &MockRestEnvelopeSpec{ctrl: ctrl}
	mock.recorder = &MockRestEnvelopeSpecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestEnvelopeSpec) EXPECT() *MockRestEnvelopeSpecMockRecorder {
	return m.recorder
}

// EnvelopeData mocks base method.
func (m *MockRestEnvelopeSpec) EnvelopeData() json.RawMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnvelopeData")
	ret0, _ := ret[0].(json.RawMessage)
	return ret0
}

// EnvelopeData indicates an expected call of EnvelopeData.
func (mr *MockRestEnvelopeSpecMockRecorder) EnvelopeData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnvelopeData", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).EnvelopeData))
}

// EnvelopeMeta mocks base method.
func (m *MockRestEnvelopeSpec) EnvelopeMeta() types.ResponseMeta {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnvelopeMeta")
	ret0, _ := ret[0].(types.ResponseMeta)
	return ret0
}

// EnvelopeMeta indicates an expected call of EnvelopeMeta.
func (mr *MockRestEnvelopeSpecMockRecorder) EnvelopeMeta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnvelopeMeta", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).EnvelopeMeta))
}

// MarshalJSON mocks base method.
func (m *MockRestEnvelopeSpec) MarshalJSON() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalJSON")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalJSON indicates an expected call of MarshalJSON.
func (mr *MockRestEnvelopeSpecMockRecorder) MarshalJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalJSON", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).MarshalJSON))
}

// New mocks base method.
func (m *MockRestEnvelopeSpec) New() contracts.RestEnvelopeSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(contracts.RestEnvelopeSpec)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockRestEnvelopeSpecMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).New))
}

// SetEnvelopeData mocks base method.
func (m *MockRestEnvelopeSpec) SetEnvelopeData(data json.RawMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnvelopeData", data)
}

// SetEnvelopeData indicates an expected call of SetEnvelopeData.
func (mr *MockRestEnvelopeSpecMockRecorder) SetEnvelopeData(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnvelopeData", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).SetEnvelopeData), data)
}

// UnmarshalJSON mocks base method.
func (m *MockRestEnvelopeSpec) UnmarshalJSON(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalJSON", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmarshalJSON indicates an expected call of UnmarshalJSON.
func (mr *MockRestEnvelopeSpecMockRecorder) UnmarshalJSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalJSON", reflect.TypeOf((*MockRestEnvelopeSpec)(nil).UnmarshalJSON), data)
}

// MockRestRegistry is a mock of RestRegistry interface.
type MockRestRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRestRegistryMockRecorder
	isgomock struct{}
}

// MockRestRegistryMockRecorder is the mock recorder for MockRestRegistry.
type MockRestRegistryMockRecorder struct {
	mock *MockRestRegistry
}

// NewMockRestRegistry creates a new mock instance.
func NewMockRestRegistry(ctrl *gomock.Controller) *MockRestRegistry {
	mock := &MockRestRegistry{ctrl: ctrl}
	mock.recorder = &MockRestRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestRegistry) EXPECT() *MockRestRegistryMockRecorder {
	return m.recorder
}

// Merge mocks base method.
func (m *MockRestRegistry) Merge(other contracts.RestRegistry) contracts.RestRegistry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", other)
	ret0, _ := ret[0].(contracts.RestRegistry)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockRestRegistryMockRecorder) Merge(other any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockRestRegistry)(nil).Merge), other)
}

// NewRequestSpec mocks base method.
func (m *MockRestRegistry) NewRequestSpec(method contracts.RestMethod) (contracts.RestDataSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRequestSpec", method)
	ret0, _ := ret[0].(contracts.RestDataSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewRequestSpec indicates an expected call of NewRequestSpec.
func (mr *MockRestRegistryMockRecorder) NewRequestSpec(method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRequestSpec", reflect.TypeOf((*MockRestRegistry)(nil).NewRequestSpec), method)
}

// ReleaseRequestSpec mocks base method.
func (m *MockRestRegistry) ReleaseRequestSpec(spec contracts.RestDataSpec) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReleaseRequestSpec", spec)
}

// ReleaseRequestSpec indicates an expected call of ReleaseRequestSpec.
func (mr *MockRestRegistryMockRecorder) ReleaseRequestSpec(spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseRequestSpec", reflect.TypeOf((*MockRestRegistry)(nil).ReleaseRequestSpec), spec)
}

// ResolveEnvelopeRequest mocks base method.
func (m *MockRestRegistry) ResolveEnvelopeRequest(method contracts.RestMethod, dataBody *[]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEnvelopeRequest", method, dataBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveEnvelopeRequest indicates an expected call of ResolveEnvelopeRequest.
func (mr *MockRestRegistryMockRecorder) ResolveEnvelopeRequest(method, dataBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEnvelopeRequest", reflect.TypeOf((*MockRestRegistry)(nil).ResolveEnvelopeRequest), method, dataBody)
}

// ResolveEnvelopeResponse mocks base method.
func (m *MockRestRegistry) ResolveEnvelopeResponse(status int, dataBody *[]byte, meta *types.ResponseMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEnvelopeResponse", status, dataBody, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveEnvelopeResponse indicates an expected call of ResolveEnvelopeResponse.
func (mr *MockRestRegistryMockRecorder) ResolveEnvelopeResponse(status, dataBody, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEnvelopeResponse", reflect.TypeOf((*MockRestRegistry)(nil).ResolveEnvelopeResponse), status, dataBody, meta)
}

// ResolveRequest mocks base method.
func (m *MockRestRegistry) ResolveRequest(body contracts.RestDataSpec, requestBody *[]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRequest", body, requestBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveRequest indicates an expected call of ResolveRequest.
func (mr *MockRestRegistryMockRecorder) ResolveRequest(body, requestBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRequest", reflect.TypeOf((*MockRestRegistry)(nil).ResolveRequest), body, requestBody)
}

// ResolveResponse mocks base method.
func (m *MockRestRegistry) ResolveResponse(status int, responseBody []byte, body *contracts.RestDataSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveResponse", status, responseBody, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveResponse indicates an expected call of ResolveResponse.
func (mr *MockRestRegistryMockRecorder) ResolveResponse(status, responseBody, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveResponse", reflect.TypeOf((*MockRestRegistry)(nil).ResolveResponse), status, responseBody, body)
}

// ResolveResponses mocks base method.
func (m *MockRestRegistry) ResolveResponses(status int, responseBody []byte, bodies *[]contracts.RestDataSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveResponses", status, responseBody, bodies)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveResponses indicates an expected call of ResolveResponses.
func (mr *MockRestRegistryMockRecorder) ResolveResponses(status, responseBody, bodies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveResponses", reflect.TypeOf((*MockRestRegistry)(nil).ResolveResponses), status, responseBody, bodies)
}

// MockRestRepository is a mock of RestRepository interface.
type MockRestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRestRepositoryMockRecorder
	isgomock struct{}
}

// MockRestRepositoryMockRecorder is the mock recorder for MockRestRepository.
type MockRestRepositoryMockRecorder struct {
	mock *MockRestRepository
}

// NewMockRestRepository creates a new mock instance.
func NewMockRestRepository(ctrl *gomock.Controller) *MockRestRepository {
	mock := &MockRestRepository{ctrl: ctrl}
	mock.recorder = &MockRestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestRepository) EXPECT() *MockRestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRestRepository) Create(ctx context.Context, request contracts.RestRequest, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRestRepositoryMockRecorder) Create(ctx, request, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRestRepository)(nil).Create), ctx, request, response)
}

// Delete mocks base method.
func (m *MockRestRepository) Delete(ctx context.Context, reqCtx types.RequestContext, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRestRepositoryMockRecorder) Delete(ctx, reqCtx, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRestRepository)(nil).Delete), ctx, reqCtx, response)
}

// Get mocks base method.
func (m *MockRestRepository) Get(ctx context.Context, reqCtx types.RequestContext, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRestRepositoryMockRecorder) Get(ctx, reqCtx, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRestRepository)(nil).Get), ctx, reqCtx, response)
}

// List mocks base method.
func (m *MockRestRepository) List(ctx context.Context, reqCtx types.RequestContext, response *contracts.RestResponses) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockRestRepositoryMockRecorder) List(ctx, reqCtx, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRestRepository)(nil).List), ctx, reqCtx, response)
}

// Save mocks base method.
func (m *MockRestRepository) Save(ctx context.Context, request contracts.RestRequest, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRestRepositoryMockRecorder) Save(ctx, request, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRestRepository)(nil).Save), ctx, request, response)
}

// Update mocks base method.
func (m *MockRestRepository) Update(ctx context.Context, request contracts.RestRequest, response *contracts.RestResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRestRepositoryMockRecorder) Update(ctx, request, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRestRepository)(nil).Update), ctx, request, response)
}

// NewRequest mocks base method.
func (m *MockRestRepository) NewRequest(method contracts.RestMethod) (*contracts.RestRequest, error) {
	// Return a permissive RestRequest with a permissive data spec so callers can
	// SetBody without requiring additional mock expectations in tests.
	return &contracts.RestRequest{Context: types.RequestContext{}, Data: &permissiveDataSpec{}}, nil
}

// NewRequest indicates an expected call of NewRequest.
func (mr *MockRestRepositoryMockRecorder) NewRequest(method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRequest", reflect.TypeOf((*MockRestRepository)(nil).NewRequest), method)
}

// NewResponse mocks base method.
func (m *MockRestRepository) NewResponse() *contracts.RestResponse {
	// Return a permissive RestResponse with permissive data specs so callers
	// can read/write fields without extra mock expectations.
	return &contracts.RestResponse{
		Context:     types.ResponseContext{},
		Information: &permissiveDataSpec{},
		Redirection: &permissiveDataSpec{},
		Problem:     &permissiveDataSpec{},
		Data:        &permissiveDataSpec{},
	}
}

// NewResponse indicates an expected call of NewResponse.
func (mr *MockRestRepositoryMockRecorder) NewResponse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewResponse", reflect.TypeOf((*MockRestRepository)(nil).NewResponse))
}
