// Code generated by MockGen. DO NOT EDIT.
// Source: ..\..\..\pkg\services\contracts\contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	"github.com/brunojet/go-infra-ports/pkg/services/contracts"
	"github.com/brunojet/go-infra-ports/pkg/types"
	"github.com/golang/mock/gomock"
)

type ServiceCreate[C any] = contracts.ServiceCreate[C]
type ServiceUpdate[U any] = contracts.ServiceUpdate[U]
type ServiceSave[C any] = contracts.ServiceSave[C]
type ServiceMeta = contracts.ServiceMeta
type ServiceResponse[R any] = contracts.ServiceResponse[R]
type ServiceResponses[R any] = contracts.ServiceResponses[R]

// MockService is a mock of Service interface.
type MockService[C, R, U any] struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder[C, R, U]
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder[C, R, U any] struct {
	mock *MockService[C, R, U]
}

// NewMockService creates a new mock instance.
func NewMockService[C, R, U any](ctrl *gomock.Controller) *MockService[C, R, U] {
	mock := &MockService[C, R, U]{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder[C, R, U]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService[C, R, U]) EXPECT() *MockServiceMockRecorder[C, R, U] {
	return m.recorder
}

// Create mocks base method.
func (m *MockService[C, R, U]) Create(ctx context.Context, request ServiceCreate[C], response *ServiceResponse[R]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder[C, R, U]) Create(ctx, request, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService[C, R, U])(nil).Create), ctx, request, response)
}

// Delete mocks base method.
func (m *MockService[C, R, U]) Delete(ctx context.Context, reqCtx types.RequestContext, response *ServiceResponse[R]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder[C, R, U]) Delete(ctx, reqCtx, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService[C, R, U])(nil).Delete), ctx, reqCtx, response)
}

// Get mocks base method.
func (m *MockService[C, R, U]) Get(ctx context.Context, reqCtx types.RequestContext, response *ServiceResponse[R]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder[C, R, U]) Get(ctx, reqCtx, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService[C, R, U])(nil).Get), ctx, reqCtx, response)
}

// List mocks base method.
func (m *MockService[C, R, U]) List(ctx context.Context, reqCtx types.RequestContext, response *ServiceResponses[R]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, reqCtx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder[C, R, U]) List(ctx, reqCtx, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService[C, R, U])(nil).List), ctx, reqCtx, response)
}

// Save mocks base method.
func (m *MockService[C, R, U]) Save(ctx context.Context, request ServiceSave[C], response *ServiceResponse[R]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServiceMockRecorder[C, R, U]) Save(ctx, request, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockService[C, R, U])(nil).Save), ctx, request, response)
}

// Update mocks base method.
func (m *MockService[C, R, U]) Update(ctx context.Context, request ServiceUpdate[U], response *ServiceResponse[R]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder[C, R, U]) Update(ctx, request, response interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService[C, R, U])(nil).Update), ctx, request, response)
}

var _ contracts.Service[any, any, any] = (*MockService[any, any, any])(nil)
