// Code generated by MockGen. DO NOT EDIT.
// Source: ..\contracts\contracts.go
//
// Generated by this command:
//
//	mockgen --source ..\contracts\contracts.go --destination mocks.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	url "net/url"
	reflect "reflect"

	contracts "github.com/brunojet/go-infra-ports/pkg/services/rest/contracts"
	gomock "go.uber.org/mock/gomock"
)

// MockRestUpstreamMapper is a mock of RestUpstreamMapper interface.
type MockRestUpstreamMapper[C, U any] struct {
	ctrl     *gomock.Controller
	recorder *MockRestUpstreamMapperMockRecorder[C, U]
	isgomock struct{}
}

// MockRestUpstreamMapperMockRecorder is the mock recorder for MockRestUpstreamMapper.
type MockRestUpstreamMapperMockRecorder[C, U any] struct {
	mock *MockRestUpstreamMapper[C, U]
}

// NewMockRestUpstreamMapper creates a new mock instance.
func NewMockRestUpstreamMapper[C, U any](ctrl *gomock.Controller) *MockRestUpstreamMapper[C, U] {
	mock := &MockRestUpstreamMapper[C, U]{ctrl: ctrl}
	mock.recorder = &MockRestUpstreamMapperMockRecorder[C, U]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestUpstreamMapper[C, U]) EXPECT() *MockRestUpstreamMapperMockRecorder[C, U] {
	return m.recorder
}

// ToUpstreamHeaders mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamHeaders(dwsHeader, upsHeader http.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamHeaders", dwsHeader, upsHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamHeaders indicates an expected call of ToUpstreamHeaders.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamHeaders(dwsHeader, upsHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamHeaders", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamHeaders), dwsHeader, upsHeader)
}

// ToUpstreamPatch mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamPatch(dwsPayload any, ids contracts.Identifiers, upsPayload *any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamPatch", dwsPayload, ids, upsPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamPatch indicates an expected call of ToUpstreamPatch.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamPatch(dwsPayload, ids, upsPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamPatch", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamPatch), dwsPayload, ids, upsPayload)
}

// ToUpstreamPost mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamPost(dwsPayload any, ids contracts.Identifiers, upsPayload *any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamPost", dwsPayload, ids, upsPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamPost indicates an expected call of ToUpstreamPost.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamPost(dwsPayload, ids, upsPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamPost", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamPost), dwsPayload, ids, upsPayload)
}

// ToUpstreamPut mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamPut(dwsPayload any, ids contracts.Identifiers, upsPayload *any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamPut", dwsPayload, ids, upsPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamPut indicates an expected call of ToUpstreamPut.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamPut(dwsPayload, ids, upsPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamPut", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamPut), dwsPayload, ids, upsPayload)
}

// ToUpstreamQuery mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamQuery(dwsQuery, upsQuery url.Values) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamQuery", dwsQuery, upsQuery)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamQuery indicates an expected call of ToUpstreamQuery.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamQuery(dwsQuery, upsQuery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamQuery", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamQuery), dwsQuery, upsQuery)
}

// MockRestDownstreamMapper is a mock of RestDownstreamMapper interface.
type MockRestDownstreamMapper struct {
	ctrl     *gomock.Controller
	recorder *MockRestDownstreamMapperMockRecorder
	isgomock struct{}
}

// MockRestDownstreamMapperMockRecorder is the mock recorder for MockRestDownstreamMapper.
type MockRestDownstreamMapperMockRecorder struct {
	mock *MockRestDownstreamMapper
}

// NewMockRestDownstreamMapper creates a new mock instance.
func NewMockRestDownstreamMapper(ctrl *gomock.Controller) *MockRestDownstreamMapper {
	mock := &MockRestDownstreamMapper{ctrl: ctrl}
	mock.recorder = &MockRestDownstreamMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestDownstreamMapper) EXPECT() *MockRestDownstreamMapperMockRecorder {
	return m.recorder
}

// ToDownstreamHeaders mocks base method.
func (m *MockRestDownstreamMapper) ToDownstreamHeaders(upsHeader, dwsHeader http.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamHeaders", upsHeader, dwsHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamHeaders indicates an expected call of ToDownstreamHeaders.
func (mr *MockRestDownstreamMapperMockRecorder) ToDownstreamHeaders(upsHeader, dwsHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamHeaders", reflect.TypeOf((*MockRestDownstreamMapper)(nil).ToDownstreamHeaders), upsHeader, dwsHeader)
}

// ToDownstreamInformation mocks base method.
func (m *MockRestDownstreamMapper) ToDownstreamInformation(statusCode int, upsPayload any, serviceMeta *contracts.ServiceMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamInformation", statusCode, upsPayload, serviceMeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamInformation indicates an expected call of ToDownstreamInformation.
func (mr *MockRestDownstreamMapperMockRecorder) ToDownstreamInformation(statusCode, upsPayload, serviceMeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamInformation", reflect.TypeOf((*MockRestDownstreamMapper)(nil).ToDownstreamInformation), statusCode, upsPayload, serviceMeta)
}

// ToDownstreamProblem mocks base method.
func (m *MockRestDownstreamMapper) ToDownstreamProblem(statusCode int, upsPayload any, serviceMeta *contracts.ServiceMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamProblem", statusCode, upsPayload, serviceMeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamProblem indicates an expected call of ToDownstreamProblem.
func (mr *MockRestDownstreamMapperMockRecorder) ToDownstreamProblem(statusCode, upsPayload, serviceMeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamProblem", reflect.TypeOf((*MockRestDownstreamMapper)(nil).ToDownstreamProblem), statusCode, upsPayload, serviceMeta)
}

// ToDownstreamRedirection mocks base method.
func (m *MockRestDownstreamMapper) ToDownstreamRedirection(statusCode int, upsPayload any, serviceMeta *contracts.ServiceMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamRedirection", statusCode, upsPayload, serviceMeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamRedirection indicates an expected call of ToDownstreamRedirection.
func (mr *MockRestDownstreamMapperMockRecorder) ToDownstreamRedirection(statusCode, upsPayload, serviceMeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamRedirection", reflect.TypeOf((*MockRestDownstreamMapper)(nil).ToDownstreamRedirection), statusCode, upsPayload, serviceMeta)
}

// ToDownstreamResponse mocks base method.
func (m *MockRestDownstreamMapper) ToDownstreamResponse(upsPayload any, dwsPayload *any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamResponse", upsPayload, dwsPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamResponse indicates an expected call of ToDownstreamResponse.
func (mr *MockRestDownstreamMapperMockRecorder) ToDownstreamResponse(upsPayload, dwsPayload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamResponse", reflect.TypeOf((*MockRestDownstreamMapper)(nil).ToDownstreamResponse), upsPayload, dwsPayload)
}

// ToDownstreamResponseMeta mocks base method.
func (m *MockRestDownstreamMapper) ToDownstreamResponseMeta(meta contracts.ResponseMeta, serviceMeta *contracts.ServiceMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamResponseMeta", meta, serviceMeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamResponseMeta indicates an expected call of ToDownstreamResponseMeta.
func (mr *MockRestDownstreamMapperMockRecorder) ToDownstreamResponseMeta(meta, serviceMeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamResponseMeta", reflect.TypeOf((*MockRestDownstreamMapper)(nil).ToDownstreamResponseMeta), meta, serviceMeta)
}

// ToDownstreamStatusCode mocks base method.
func (m *MockRestDownstreamMapper) ToDownstreamStatusCode(upsStatusCode int, dwsStatusCode *int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamStatusCode", upsStatusCode, dwsStatusCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamStatusCode indicates an expected call of ToDownstreamStatusCode.
func (mr *MockRestDownstreamMapperMockRecorder) ToDownstreamStatusCode(upsStatusCode, dwsStatusCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamStatusCode", reflect.TypeOf((*MockRestDownstreamMapper)(nil).ToDownstreamStatusCode), upsStatusCode, dwsStatusCode)
}
