// Code generated by MockGen. DO NOT EDIT.
// Source: contracts\contracts.go

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	url "net/url"
	reflect "reflect"

	contracts "github.com/brunojet/go-infra-ports/pkg/services/rest/contracts"
	gomock "github.com/golang/mock/gomock"
)

// MockRestUpstreamMapper is a mock of RestUpstreamMapper interface.
type MockRestUpstreamMapper[C, U any] struct {
	ctrl     *gomock.Controller
	recorder *MockRestUpstreamMapperMockRecorder[C, U]
}

// MockRestUpstreamMapperMockRecorder is the mock recorder for MockRestUpstreamMapper.
type MockRestUpstreamMapperMockRecorder[C, U any] struct {
	mock *MockRestUpstreamMapper[C, U]
}

// NewMockRestUpstreamMapper creates a new mock instance.
func NewMockRestUpstreamMapper[C, U any](ctrl *gomock.Controller) *MockRestUpstreamMapper[C, U] {
	mock := &MockRestUpstreamMapper[C, U]{ctrl: ctrl}
	mock.recorder = &MockRestUpstreamMapperMockRecorder[C, U]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestUpstreamMapper[C, U]) EXPECT() *MockRestUpstreamMapperMockRecorder[C, U] {
	return m.recorder
}

// ToUpstreamHeaders mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamHeaders(reqHeader, upsHeader http.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamHeaders", reqHeader, upsHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamHeaders indicates an expected call of ToUpstreamHeaders.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamHeaders(reqHeader, upsHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamHeaders", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamHeaders), reqHeader, upsHeader)
}

// ToUpstreamPatch mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamPatch(payload U, ids contracts.Identifiers, upsPayload *contracts.RestRequestSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamPatch", payload, ids, upsPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamPatch indicates an expected call of ToUpstreamPatch.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamPatch(payload, ids, upsPayload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamPatch", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamPatch), payload, ids, upsPayload)
}

// ToUpstreamPost mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamPost(payload C, ids contracts.Identifiers, upsPayload *contracts.RestRequestSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamPost", payload, ids, upsPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamPost indicates an expected call of ToUpstreamPost.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamPost(payload, ids, upsPayload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamPost", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamPost), payload, ids, upsPayload)
}

// ToUpstreamPut mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamPut(payload C, ids contracts.Identifiers, upsPayload *contracts.RestRequestSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamPut", payload, ids, upsPayload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamPut indicates an expected call of ToUpstreamPut.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamPut(payload, ids, upsPayload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamPut", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamPut), payload, ids, upsPayload)
}

// ToUpstreamQuery mocks base method.
func (m *MockRestUpstreamMapper[C, U]) ToUpstreamQuery(reqQuery, upsQuery url.Values) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUpstreamQuery", reqQuery, upsQuery)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToUpstreamQuery indicates an expected call of ToUpstreamQuery.
func (mr *MockRestUpstreamMapperMockRecorder[C, U]) ToUpstreamQuery(reqQuery, upsQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUpstreamQuery", reflect.TypeOf((*MockRestUpstreamMapper[C, U])(nil).ToUpstreamQuery), reqQuery, upsQuery)
}

// MockRestDownstreamMapper is a mock of RestDownstreamMapper interface.
type MockRestDownstreamMapper[R any] struct {
	ctrl     *gomock.Controller
	recorder *MockRestDownstreamMapperMockRecorder[R]
}

// MockRestDownstreamMapperMockRecorder is the mock recorder for MockRestDownstreamMapper.
type MockRestDownstreamMapperMockRecorder[R any] struct {
	mock *MockRestDownstreamMapper[R]
}

// NewMockRestDownstreamMapper creates a new mock instance.
func NewMockRestDownstreamMapper[R any](ctrl *gomock.Controller) *MockRestDownstreamMapper[R] {
	mock := &MockRestDownstreamMapper[R]{ctrl: ctrl}
	mock.recorder = &MockRestDownstreamMapperMockRecorder[R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestDownstreamMapper[R]) EXPECT() *MockRestDownstreamMapperMockRecorder[R] {
	return m.recorder
}

// ToDownstreamHeaders mocks base method.
func (m *MockRestDownstreamMapper[R]) ToDownstreamHeaders(upsHeader, downstreamHeader http.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamHeaders", upsHeader, downstreamHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamHeaders indicates an expected call of ToDownstreamHeaders.
func (mr *MockRestDownstreamMapperMockRecorder[R]) ToDownstreamHeaders(upsHeader, downstreamHeader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamHeaders", reflect.TypeOf((*MockRestDownstreamMapper[R])(nil).ToDownstreamHeaders), upsHeader, downstreamHeader)
}

// ToDownstreamInformation mocks base method.
func (m *MockRestDownstreamMapper[R]) ToDownstreamInformation(statusCode int, upsPayload contracts.RestResponseSpec, serviceMeta *contracts.ServiceMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamInformation", statusCode, upsPayload, serviceMeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamInformation indicates an expected call of ToDownstreamInformation.
func (mr *MockRestDownstreamMapperMockRecorder[R]) ToDownstreamInformation(statusCode, upsPayload, serviceMeta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamInformation", reflect.TypeOf((*MockRestDownstreamMapper[R])(nil).ToDownstreamInformation), statusCode, upsPayload, serviceMeta)
}

// ToDownstreamProblem mocks base method.
func (m *MockRestDownstreamMapper[R]) ToDownstreamProblem(statusCode int, upsPayload contracts.RestResponseSpec, serviceMeta *contracts.ServiceMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamProblem", statusCode, upsPayload, serviceMeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamProblem indicates an expected call of ToDownstreamProblem.
func (mr *MockRestDownstreamMapperMockRecorder[R]) ToDownstreamProblem(statusCode, upsPayload, serviceMeta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamProblem", reflect.TypeOf((*MockRestDownstreamMapper[R])(nil).ToDownstreamProblem), statusCode, upsPayload, serviceMeta)
}

// ToDownstreamRedirection mocks base method.
func (m *MockRestDownstreamMapper[R]) ToDownstreamRedirection(statusCode int, upsPayload contracts.RestResponseSpec, serviceMeta *contracts.ServiceMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamRedirection", statusCode, upsPayload, serviceMeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamRedirection indicates an expected call of ToDownstreamRedirection.
func (mr *MockRestDownstreamMapperMockRecorder[R]) ToDownstreamRedirection(statusCode, upsPayload, serviceMeta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamRedirection", reflect.TypeOf((*MockRestDownstreamMapper[R])(nil).ToDownstreamRedirection), statusCode, upsPayload, serviceMeta)
}

// ToDownstreamResponse mocks base method.
func (m *MockRestDownstreamMapper[R]) ToDownstreamResponse(upsPayload any, payload *R) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamResponse", upsPayload, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamResponse indicates an expected call of ToDownstreamResponse.
func (mr *MockRestDownstreamMapperMockRecorder[R]) ToDownstreamResponse(upsPayload, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamResponse", reflect.TypeOf((*MockRestDownstreamMapper[R])(nil).ToDownstreamResponse), upsPayload, payload)
}

// ToDownstreamResponseMeta mocks base method.
func (m *MockRestDownstreamMapper[R]) ToDownstreamResponseMeta(meta contracts.ResponseMeta, serviceMeta *contracts.ServiceMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamResponseMeta", meta, serviceMeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamResponseMeta indicates an expected call of ToDownstreamResponseMeta.
func (mr *MockRestDownstreamMapperMockRecorder[R]) ToDownstreamResponseMeta(meta, serviceMeta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamResponseMeta", reflect.TypeOf((*MockRestDownstreamMapper[R])(nil).ToDownstreamResponseMeta), meta, serviceMeta)
}

// ToDownstreamStatusCode mocks base method.
func (m *MockRestDownstreamMapper[R]) ToDownstreamStatusCode(statusCode int, downstreamStatusCode *int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToDownstreamStatusCode", statusCode, downstreamStatusCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToDownstreamStatusCode indicates an expected call of ToDownstreamStatusCode.
func (mr *MockRestDownstreamMapperMockRecorder[R]) ToDownstreamStatusCode(statusCode, downstreamStatusCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToDownstreamStatusCode", reflect.TypeOf((*MockRestDownstreamMapper[R])(nil).ToDownstreamStatusCode), statusCode, downstreamStatusCode)
}
